name: mnemonic_label
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: "3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
